# Generated by Django 5.2 on 2025-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='chema',
            new_name='schema',
        ),
    ]
